name: woodnet-showcase
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pytorch
  - cpuonly
  - zarr
  - h5py
  - tqdm
  - ipywidgets
  - ipympl
  - k3d
  - rich
  - ruamel.yaml