name: woodnet-showcase
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pytorch
  - cpuonly
  - pandas
  - zarr
  - h5py
  - tqdm
  - tensorboard
  - ipywidgets
  - ipympl
  - k3d
  - scikit-learn
  - scikit-image
  - tensorboard
  - seaborn
  - rich
  - monai
  - pillow
  - pytest
  - ruamel.yaml
  - frozendict